version: '3.7'

services:
  wfbot:
    image: trksteam/wfbot
    pull_policy: always
    volumes: 
        - ./WFBotConnector:/app/WFBotConnector
        - ./WFBotPlugins:/app/WFBotPlugins
        - ./WFBotLogs:/app/WFBotLogs
        - ./WFOfflineResource:/app/WFOfflineResource
        - ./WFBotConfigs:/app/WFBotConfigs
    network_mode: host
